# Caratteristiche all'ingresso  {#ccc .tabset .tabset-fade .tabset-pills}

<!-- cat("## Overview {-}") -->

<!--Chronic complex condition definition was taken by the paper of Feudtner C et al: “Pediatric Deaths Attributable to
Complex Chronic Conditions: A Population-Based Study of Washington State, 1980-1997” published in Pediatrics in
2000 (106:205-209) and was defined as “any medical condition that can be reasonably expected to last at least 12
months, unless death intervenes, and to involve either one or more different organ systems”.
CCC were divided within 10 categories (defined macrodiagnosis): neurologic, neuromuscular, cardiologic,
oncoematologic, respiratory, syndromic, renal, metabolic, malformation, other.
Moreover, the system allows to record the specific chronic disease --> 



## Comorbidità {.tabset .tabset-dropdown}

### Comorbidità 
```{r, eval=!params$export}
admissionReportUI("m_mal_cronica")
```

```{r, context = "server", eval=!params$export}
admissionReport(
  "m_mal_cronica",
  data = data_ranged[["full_filtered"]],
  type = "centervar",
  what = "mal_cronica"
)
```

### Macro-diagnosi
```{r, eval=!params$export}
admissionReportUI("m_macro")
```

```{r, context = "server", eval=!params$export}
admissionReport(
  "m_macro",
  data = data_ranged[["full_filtered"]],
  type = "checkbox",
  dict = comorb  # internal db in data-raw/internal-data.R
)
```


<!--## CCC {.tabset .tabset-dropdown}  -->

<!--### Rate by center  -->

<!--### Type  -->

<!--### Age --> 

## POPC {.tabset .tabset-dropdown}
```{r, eval=!params$export}
admissionReportUI("m_popc")
```

```{r, context = "server", eval=!params$export}
admissionReport(
  "m_popc",
  data = data_ranged[["full_filtered"]],
  type = "centervar",
  what = "popc"
)
```
## Insufficienze d'organo  {.tabset .tabset-dropdown}

### Insufficienze d'organo 
```{r, eval=!params$export}
admissionReportUI("m_insuff_organo7")
```

```{r, context = "server", eval=!params$export}
admissionReport(
  "m_insuff_organo7",
  data = data_ranged[["full_filtered"]],
  type = "centervar",
  what = "insuff_organo7"
)
```

### Insufficienze d'organo macro
```{r, eval=!params$export}
admissionReportUI("m_insuff_organo")
```

```{r, context = "server", eval=!params$export}
admissionReport(
  "m_insuff_organo",
  data = data_ranged[["full_filtered"]],
  type = "checkbox",
  dict = insuff_organo  # internal db in data-raw/internal-data.R
)
```



## PIM3 {.tabset .tabset-dropdown}


### PIM3
```{r, eval=!params$export}
admissionReportUI("adm_pim")
```

```{r, context = "server", eval=!params$export}
admissionReport(
  "adm_pim",
  data = data_ranged[["full_filtered"]],
  type = "centervar",
  what = "pim"
)
```

